n = input('Digite uma algo:')
print('{} É alfabético?'.format(n), n.isalpha())
print('Qual a classe de {} classe?'.format(n), type(n))
print('{} é um número?'.format(n), n.isnumeric())
print('{} é alfanúmerico?'.format(n), n.isalnum())
print('{} está em maiúsculo?'.format(n), n.isupper())
print('{} está em minúsculo?'.format(n), n.islower())
print('{} está capitalizado?'.format(n), n.istitle())
print('{} tem espaços?'.format(n), n.isspace())
